"""initial: stations, tractors

Revision ID: 3112f42d1e35
Revises:
Create Date: 2026-06-21 12:45:39.904932

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3112f42d1e35"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stations",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "video_dir", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "roi_polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_entry_zone", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stations_code"), "stations", ["code"], unique=True)
    op.create_table(
        "tractors",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "aruco_ids",
            postgresql.ARRAY(sa.Integer()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "primary_aruco_id",
            sa.Integer(),
            sa.Computed("aruco_ids[1]", persisted=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "array_length(aruco_ids, 1) >= 1", name="chk_tractors_aruco_ids_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_tractors_primary_aruco", "tractors", ["primary_aruco_id"], unique=True
    )
    # GIN-индекс для поиска трактора по любому из его aruco_ids:
    #   SELECT * FROM tractors WHERE $1 = ANY(aruco_ids);
    op.create_index(
        "ix_tractors_aruco_ids", "tractors", ["aruco_ids"], postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tractors")
    op.drop_index("uq_tractors_primary_aruco", table_name="tractors")
    op.drop_index("ix_tractors_aruco_ids", table_name="tractors")
    op.drop_index(op.f("ix_stations_code"), table_name="stations")
    op.drop_table("stations")
    # ### end Alembic commands ###
