"""video_files

Revision ID: e31b2289c092
Revises: 3112f42d1e35
Create Date: 2026-06-21 12:55:47.115360

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e31b2289c092"
down_revision: str | None = "3112f42d1e35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_files",
        sa.Column(
            "storage_uri", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "INVALID",
                name="videostatus",
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frames_processed", sa.Integer(), nullable=False),
        sa.Column("triggers_fired", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("events_found", sa.Integer(), nullable=False),
        sa.CheckConstraint("started_at < ended_at", name="chk_video_times"),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name="chk_video_duration",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        "ix_video_files_station_started",
        "video_files",
        ["station_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_video_files_status",
        "video_files",
        ["status"],
        unique=False,
        postgresql_where="status IN ('FAILED', 'PROCESSING')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_video_files_status",
        table_name="video_files",
        postgresql_where="status IN ('FAILED', 'PROCESSING')",
    )
    op.drop_index("ix_video_files_station_started", table_name="video_files")
    op.drop_table("video_files")
    # ### end Alembic commands ###
